base_url = "https://maitraya-linux.github.io"

title = "fishy cabinet"
description = "[n., bn]: a cabinet of whispers [n, en]: a cabinet which smells of the sea"

generate_feeds = true
compile_sass = false
build_search_index = true

[markdown]

[extra]
webserver_sends_csp_headers = true

[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = true

[[extra.main_menu]]
name = "posts"
url = "@/_index.md"

[[extra.main_menu]]
name = "search"
url = "@/search/_index.md"

[[extra.main_menu]]
name = "essentials"
url = "@/essentials/_index.md"

[[extra.main_menu]]
name = "de"
url = "@/german/_index.md"

[[extra.main_menu]]
name = "about"
url = "@/about/_index.md"
